@server = http://localhost:8000
@qId = 4


### '전체' 질문 조회
GET {{server}}

### '특정' 질문 조회
GET {{server}}/question/{{qId}}

### 질문 수정
PATCH {{server}}/question/{{qId}}/edit
Content-Type: application/json; charset=utf-8

# 성공하면 1, 실패하면 0
{
    "title": "제목 수정합니다",
    "content" : "내용 수정합니다"
}

### 질문 추가
POST {{server}}/question/create
# 인코딩
Content-Type: application/json; charset=utf-8

# body 쓸 때는 한 줄 띄어줘야 함
{
   "qId" : 10,
    "title": "제목",
    "content": "내용",
    "viewCount": 1,
    "likeCount": 1,
    "qType": "프론트"
}

### 특정 질문 삭제
DELETE {{server}}/question/{{qId}}/delete

@uId = hj

### 회원가입 시 db 저장
POST {{server}}/users
Content-Type: application/json; charset=UTF-8

{
    "uId": "hjj",
    "pw" : "1",
    "uName" : "hj",
    "email" : "jin@gmail.com"
}


### 회원 조회
GET {{server}}/users/{{uId}}

### 특정 사용자의 정보 변경 - pw, uName 변경 가능
PATCH {{server}}/users/{{uId}}/userInfo
Content-Type: application/json; charset=UTF-8

{
    "pw" : "1111",
    "uName" : "1111"
}

### 회원 탈퇴
DELETE {{server}}/users/{{uId}}



