@server = http://localhost:8000
@qId = 4


### '전체' 질문 조회
GET {{server}}/questions

### '특정' 질문 조회
GET {{server}}/question/{{qId}}

### 질문 수정
PATCH {{server}}/questions/{{qId}}/question
Content-Type: application/json; charset=utf-8

# 성공하면 1, 실패하면 0
{
    "title": "제목 수정합니다",
    "content" : "내용 수정합니다"
}

### 질문 추가
POST {{server}}/question
# 인코딩
Content-Type: application/json; charset=utf-8

# body 쓸 때는 한 줄 띄어줘야 함
{
   "qId" : 10,
    "title": "제목",
    "content": "내용",
    "viewCount": 1,
    "likeCount": 1,
    "type": "프론트"
}

### 특정 질문 삭제
DELETE {{server}}/questions/{{qId}}