exports.main = (req, res) => {

    const isLogin = req.session.user ? true : false;

    const sampleData = [
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
        {
            type: "자유",
            time: "2023-01-01",
            name: "kuromi",
            title: "내가 첫글이야?",
            content: "가나다라마바사아자차카타파하",
        },
    ];

    res.render("index", { type: "Q&A", data: sampleData, isLogin });
};
